"""
chirp_phase_force_b1_w3.py
==========================

Relative-phase force experiment using the chirp-aware frozen-age templates
generated by build_chirp_template_b1_w3.py.

For each template (spp160 / spp320) and kappa R ~ 7,8,9,10:
  * scan 64 relative phases delta,
  * average over 256 common phases theta,
  * compute exact midpoint interaction stress,
  * decompose Fbar(delta) into phase harmonics,
  * separately identify the quadratic n=1,3,5,7 contributions.

The purpose is to suppress spectral leakage caused by the slow chirp of the
quasi-breather before interpreting higher phase harmonics as physical radiation.
"""

from pathlib import Path
import csv, math
import numpy as np
import matplotlib.pyplot as plt

HERE=Path(__file__).resolve().parent
H=(1,3,5,7)

def G(u,b=1.0):
    y=1-np.cos(u)
    return 2*y/(1+np.sqrt(1+b*b*y))

def fit_delta(delta,F,nmax=8):
    cols=[np.ones_like(delta)]
    for n in range(1,nmax+1):
        cols += [np.cos(n*delta),np.sin(n*delta)]
    A=np.column_stack(cols)
    c,*_=np.linalg.lstsq(A,F,rcond=None)
    fit=A@c
    z={"c0":float(c[0]),"rms":float(np.sqrt(np.mean((F-fit)**2)))}
    for n in range(1,nmax+1):
        z[f"cos{n}"]=float(c[1+2*(n-1)])
        z[f"sin{n}"]=float(c[2+2*(n-1)])
    return z

def run(tag):
    d=np.load(HERE/f"chirp_template_{tag}.npz")
    x=d["x"]; CU=d["CU"]; CV=d["CV"]; CUx=d["CUx"]
    omega=float(d["omega"]); kappa=float(d["kappa"])
    N=x.size; dx=x[1]-x[0]; ic=N//2

    def point(theta,idx):
        u=float(CU[0,idx]); v=float(CV[0,idx]); ux=float(CUx[0,idx])
        for n in H:
            j=1+2*H.index(n)
            c=math.cos(n*theta); s=math.sin(n*theta)
            u += CU[j,idx]*c+CU[j+1,idx]*s
            v += CV[j,idx]*c+CV[j+1,idx]*s
            ux += CUx[j,idx]*c+CUx[j+1,idx]*s
        return u,v,ux

    def harmonic(n,theta,idx):
        j=1+2*H.index(n); c=math.cos(n*theta); s=math.sin(n*theta)
        return (float(CU[j,idx]*c+CU[j+1,idx]*s),
                float(CV[j,idx]*c+CV[j+1,idx]*s),
                float(CUx[j,idx]*c+CUx[j+1,idx]*s))

    def exact_cross(L,R):
        uL,vL,xL=L; uR,vR,xR=R
        return float(G(uL+uR)-G(uL)-G(uR)-vL*vR-xL*xR)

    def qcross(L,R):
        uL,vL,xL=L; uR,vR,xR=R
        return float(uL*uR-vL*vR-xL*xR)

    nd=64; nt=256
    deltas=2*np.pi*np.arange(nd)/nd
    thetas=2*np.pi*np.arange(nt)/nt
    rows=[]; curves={}

    for target in (7.,8.,9.,10.):
        m=max(1,int(round((target/kappa)/(2*dx))))
        R=2*m*dx; kr=kappa*R; ip=ic+m; im=ic-m
        F=np.empty(nd); Fq=np.empty(nd)
        Fh={n:np.empty(nd) for n in H}

        for jd,delta in enumerate(deltas):
            vf=[]; vq=[]; vh={n:[] for n in H}
            for th in thetas:
                Lp=point(th-delta/2,ip); Rp=point(th+delta/2,im)
                vf.append(exact_cross(Lp,Rp)); vq.append(qcross(Lp,Rp))
                for n in H:
                    vh[n].append(qcross(harmonic(n,th-delta/2,ip),
                                        harmonic(n,th+delta/2,im)))
            F[jd]=np.mean(vf); Fq[jd]=np.mean(vq)
            for n in H: Fh[n][jd]=np.mean(vh[n])

        ff=fit_delta(deltas,F)
        fhs={n:fit_delta(deltas,Fh[n]) for n in H}
        nl=fit_delta(deltas,F-Fq)

        rows.append({
            "tag":tag,"target_kappaR":target,"actual_kappaR":kr,"R":R,
            "omega":omega,"kappa":kappa,
            "F0":float(F[0]),"Fpi2":float(F[nd//4]),"Fpi":float(F[nd//2]),
            "cos1":ff["cos1"],"cos2":ff["cos2"],"cos3":ff["cos3"],
            "cos5":ff["cos5"],"cos7":ff["cos7"],
            "h1_cos1":fhs[1]["cos1"],"h3_cos3":fhs[3]["cos3"],
            "h5_cos5":fhs[5]["cos5"],"h7_cos7":fhs[7]["cos7"],
            "nonlinear_cos2":nl["cos2"],
            "null_ratio":float(F[nd//4]/abs(F[0])),
            "cos_rms_ratio":
                float(np.sqrt(np.mean((F-F[0]*np.cos(deltas))**2))/abs(F[0]))
        })
        curves[target]=F
    return rows,deltas,curves

def main():
    r160,_,_=run("spp160")
    r320,deltas,c320=run("spp320")
    rows=r160+r320

    with open(HERE/"chirp_phase_force_summary_b1_w3.csv","w",newline="") as f:
        w=csv.DictWriter(f,fieldnames=list(rows[0].keys()))
        w.writeheader(); w.writerows(rows)

    plt.figure(figsize=(7.5,5.1))
    for target in (7.,8.,9.,10.):
        F=c320[target]
        plt.plot(deltas/np.pi,F/F[0],"o-",ms=3,
                 label=fr"$\kappa R\simeq{target:g}$")
    dd=np.linspace(0,2*np.pi,500)
    plt.plot(dd/np.pi,np.cos(dd),"--",label=r"$\cos\delta$")
    plt.xlabel(r"$\delta/\pi$")
    plt.ylabel(r"$\overline{F}(\delta)/\overline{F}(0)$")
    plt.grid(True); plt.legend(); plt.tight_layout()
    plt.savefig(HERE/"chirp_phase_cosine_law_spp320.png",dpi=180)
    plt.close()

if __name__=="__main__":
    main()
